# fly.toml app configuration file generated for sefaria-ai on 2024-06-19T08:46:29-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sefaria-ai'
primary_region = 'ord'

[build]

[http_service]
internal_port = 8501
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
